
project_id = "xngdlzpfbyfqqjdylmnb"

[functions.flight-prices]
verify_jwt = false

[functions.flight-prices.secrets]
AMADEUS_API_KEY = "tXAyTZgku1b3VnKfUbjukzUgClFAik0e"
AMADEUS_API_SECRET = "Ym91W1skpDYgTOHH"
