// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xngdlzpfbyfqqjdylmnb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhuZ2RsenBmYnlmcXFqZHlsbW5iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyMzI1NzcsImV4cCI6MjA2MjgwODU3N30.OfDS_edJT16BCkwsvHIBBdtFqsl5KwUAMddcVMZxPuM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);